src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CourseRepository::class)]
class Course
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::FLOAT)]
    private ?float $price = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'favBy')]
    private Collection $favBy;

    #[ORM\ManyToOne(inversedBy: 'createdCourses')]
    #[ORM\JoinColumn(nullable: false, onDelete:"CASCADE")]
    private ?User $creator = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $imagePath = null;

    public function __construct()
    {
        $this->favBy = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }


    public function setTitle(string $title): static {
        $this->title = $title;
        return $this;
    }



    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFavCourses(): Collection
    {
        return $this->favBy;
    }

    public function addFavCourse(User $favCourse): static
    {
        if (!$this->favBy->contains($favCourse)) {
            $this->favBy->add($favCourse);
            $favCourse->addFavCourse($this);
        }

        return $this;
    }

    public function removeFavCourse(User $favCourse): static
    {
        if ($this->favBy->removeElement($favCourse)) {
            $favCourse->removeFavCourse($this);
        }

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(string $imagePath): static
    {
        $this->imagePath = $imagePath;

        return $this;
    }
}

src/Controller/CourseController.php
<?php

namespace App\Controller;

use App\Entity\Course;
use App\Entity\User;
use App\Form\CreateCourseFormType;
use App\Repository\CourseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CourseController extends AbstractController{
    private CourseRepository $courseRepository;
    private EntityManagerInterface $em;
    private User|null $user;
    private PaginatorInterface $paginator;

    public function __construct(CourseRepository $courseRepository, EntityManagerInterface $em, PaginatorInterface $paginator, Security $security) {
        $this->courseRepository = $courseRepository;
        $this->em = $em;
        $this->paginator = $paginator;
        $this->user = $security->getUser() ?? null;
    }

    
    #[Route('/home', name: 'app_home')]
    public function index(Request $request): Response{
        $courses = $this->courseRepository->findAll();

        $limit = $request->query->getInt('limit', 10);  
        $pagination = $this->paginator->paginate(
            $courses, 
            $request->query->getInt('page', 1),
            $limit,
        );

        return $this->render('course/list.html.twig', [
            'pagination' => $pagination,
            'limit' => $limit,
            'user' => $this->user,
        ]);
    }

    #[Route('/course/new', name:'app_new_course')]
    public function newCourse(Request $request): Response{
        $course = new Course();
        $form = $this->createForm(CreateCourseFormType::class, $course);
        $form->handleRequest($request);

        // the CreateCourseFormType::class Already validates all the required fields for us
        if ($form->isSubmitted() && $form->isValid()) {

            /** @var \Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $form->get('image')->getData();

            // set a unique filename
            $newFilename = uniqid() . '.' . $file->guessExtension();
            $file->move(
                $this->getParameter('courses_images_uploads_full_directory'),
                $newFilename
            );

            // upload image to the dynamic images directory
            $course->setImagePath('/' . $this->getParameter('courses_images_uploads_directory') . $newFilename);

            // set the new course's creator as the current user
            $course->setCreator($this->user);

            $this->em->persist($course);
            $this->em->flush();

            return $this->redirectToRoute('app_home');
        }
        return $this->render('course/new.html.twig', [
            'user' => $this->user,
            'form' => $form
        ]);
    }

    #[Route('/fav', name:'app_course_favs')]
    public function showFavourites(): Response{
        return $this->render("course/fav.courses.html.twig", [
            'user' => $this->user,
        ]
        );
    }

    // no need for slugger here
    #[Route('/fav/add/{id}', name:'app_add_fav_course')]
    public function addFavouriteCourse(int $id): Response{
        $course = $this->courseRepository->find($id);

        if ($course) {
            // throw $this->createNotFoundException('The course does not exist');
            $this->user->addFavCourse($course);
            $this->em->persist($this->user);
            $this->em->flush();
        }else{
            // redirect to not found page
            return $this->redirectToRoute('app_not_found');
        }

        return $this->redirectToRoute('app_course_favs');
    }

    // no need for slugger here
    #[Route('/fav/remove/{id}', name:'app_remove_fav_course')]
    public function removeFavouriteCourse(int $id): Response{
        $course = $this->courseRepository->find($id);

        if ($course) {
            $this->user->removeFavCourse($course);
            $this->em->persist($this->user);
            $this->em->flush();
        }else{
            // redirect to not found page
            return $this->redirectToRoute('app_not_found');
        }

        return $this->redirectToRoute('app_course_favs');
    }
}

templates/course/fav.course.html.twig
<div class="single-fav-course-container bg-light d-flex flex-column">
    <div class="single-course-card-image-container w-100 position-relative">
        <img src="{{asset(course.imagePath)}}" class="w-100 h-100 rounded">

        <button class="btn btn-outline-primary text-light 
                        rounded-circle border-0 position-absolute" 
                onclick="window.location.replace('/fav/remove/{{course.id}}')">
            <i class="fa fa-heart text-dark"></i>
        </button>
    </div>

    
    <div class="w-100 p-4 pb-0">
        <small class="fs--3">Graphic Design</small>
        <h6 class="text-wrap fw-bolder mt-2">{{course.title}}</h6>
        <div class="d-flex flex-column justify-content-between mt-4 gap-2">
            <div class="d-flex flex-column gap-2">
                <div class="d-flex align-items-center gap-2">
                    <i class="fa fa-book"></i>
                    <span>9/12 Lessons Left</span>
                </div>
                <div class="single-fav-course-loading">
                    <div class="single-fav-course-loading-completed" style="width: 80%;"></div>
                </div>
            </div>
            <span>{{course.creator.fname}} {{course.creator.lname}}</span>
        </div>
    </div>
</div>

templates/course/fav.courses.html.twig
{# This page doesnt extend page.html.twig because it has specific content #}
{% extends "base.html.twig" %}

{% block body %}
<div class="d-flex">
    {% include("widgets/sidebar.html.twig") %}
   <div class="col-10 d-flex flex-column">
        {{ include("widgets/fav.header.html.twig") }}

        <div class="h-100 container d-flex flex-wrap gap-4 p-4 rounded">
        {% for course in user.favCourses %}
            {% include "course/fav.course.html.twig" with {'course' : course} %}
        {% endfor %}
        </div>
   </div>

</div>

{% include "widgets/footer.html.twig" %} 
{% endblock %}

templates/course/list.html.twig
{% extends 'page.html.twig' %} 
{% block title %}Homepage{% endblock %}

{% block content %}
<div class="container position-relative">
    <h2 class="mt-2">Language Course</h2>
    {% if user %}
      <a href="/course/new">
          <button class="btn btn-primary mt-2 position-absolute top-0 end-0">
              <i class="fa fa-plus"></i>
              <span>Add Course</span>
          </button>
      </a>
    {% endif %}
    
  
      <div class="d-flex justify-content-center flex-wrap gap-4 mt-4">
          {% for course in pagination %}
              {% include "course/single.course.html.twig" with {'course': course, 'user' : user} %}
          {% else %}
              <span>No courses found.</span>
          {% endfor %}
      </div>
  
      <div class="pagination d-flex justify-content-between align-items-center my-3">
          <div class="col-3 d-flex justify-content-between form-group align-items-center">
              <label for="limit">Showing:</label>
              <select id="limit" name="limit" class="form-select w-50" onchange="location = this.value;">
                  <option value="?limit=5" {% if limit == 5 %}selected{% endif %}>5 Per Page</option>
                  <option value="?limit=10" {% if limit == 10 %}selected{% endif %}>10 Per Page</option>
                  <option value="?limit=25" {% if limit == 25 %}selected{% endif %}>25 Per Page</option>
                  <option value="?limit=50" {% if limit == 50 %}selected{% endif %}>50 Per Page</option>
              </select>
              <span>Of ({{pagination.count}}) data</span>
          </div>
          {{ knp_pagination_render(pagination, 'widgets/pagination/course.table.html.twig') }}
      </div>
  </div>
{% endblock %}

templates/course/new.html.twig
{% extends "base.html.twig" %}
{% block title %}Create new Course!{% endblock %}
{% form_theme form 'form/signup.errors.html.twig' %}    

{% block body %}
{{ include("widgets/header.html.twig" , {'user' : user} ) }}
    
    <div class="container" id="course-new-container">
        {# start: form container #}
      <div class="bg-white p-5 rounded">
        {{ form_start(form) }}
        <h3 class="fw-bolder">Add course</h3>

        {# start: title #}
        <div class="row">
            <div class="form-group my-1">
                <label for="{{form.title.vars.id}}">{{ form_label(form.title) }}</label>
                {{ form_widget(form.title) }}
                {{ form_errors(form.title) }}
            </div>
        </div>
        {# end: title #}
        
        {# start: price #}
        <div class="row">
            <div class="form-group my-1">
                <label for="{{form.price.vars.id}}">{{ form_label(form.price) }}</label>
                {{ form_widget(form.price) }}
                {{ form_errors(form.price) }}
            </div>
        </div>
        {# end: price #}
        
        {# start: image #}
        <div class="row">
            <div class="form-group my-1">
                <label for="{{form.image.vars.id}}">{{ form_label(form.image) }}</label>
                {{ form_widget(form.image) }}
                {{ form_errors(form.image) }}
            </div>
        </div>
        {# end: image #}
        

        <button type="submit" class="btn btn-primary col-12 mt-4">submit</button>
        
        {{ form_end(form) }}
      </div>
      {# end: form container #}
    </div>

    {% include "widgets/footer.html.twig" %} 
{% endblock %}

templates/course/single.course.html.twig
<div class="single-course-card col-2 d-flex flex-column">
    <div class="single-course-card-image-container w-100 position-relative">
        <img src="{{asset(course.getImagePath())}}" class="w-100 h-100 rounded">

        <button class="btn btn-{% if user and user.favCourses.contains(course) %}primary{% else %}light{% endif %} rounded-circle position-absolute" 
                onclick="window.location.replace('/fav/add/{{course.id}}')">
            <i class="far fa-heart"></i>
        </button>

        <div class="single-course-teacher-container text-light fw-medium position-absolute">
            <img src="{{asset('images/users/1.png')}}">
            {{course.getCreator().getFname()}} {{course.getCreator().getLname()}}
        </div>
    </div>

    
    <div class="w-100 p-4 pb-0">
        <h4 class="text-wrap">{{course.title}}</h4>
        <div class="col-10 d-flex justify-content-between mt-4">
            <div class="d-flex align-items-center gap-2">
                <div class="single-course-card-circle-option"><i class="fa fa-briefcase"></i></div>
                <span>Advance</span>
            </div>
            <div class="d-flex align-items-center gap-2">
                <div class="single-course-card-circle-option"><i class="fa fa-users"></i></div>
                <span>14</span>
            </div>
            <div class="d-flex align-items-center gap-2">
                <div class="single-course-card-circle-option"><i class="fa fa-star text-warning"></i></div>
                <span>5.0</span>
            </div>
        </div>
    </div>

    <hr>

    <div class="w-100 px-4 py-0 d-flex justify-content-between align-items-center">
        <h4 class="fw-bold">${{course.price}}</h4>

        <a href="#" class="text-decoration-none text-reset">
            <i class="fa fa-shopping-bag me-1"></i>
            <span class="fw-medium">Add to cart</span>
        </a>
        
    </div>
</div>